
import * as LucideIcons from 'lucide-react';

const materialToLucide = {
    'refresh': 'RefreshCw',
    'psychology': 'Brain',
    'progress_activity': 'Loader2',
    'library_books': 'Library',
    'add': 'Plus',
    'account_tree': 'Network',
    'smart_toy': 'Bot',
    'school': 'GraduationCap',
    'auto_awesome': 'Sparkles',
    'delete': 'Trash2',
    'search': 'Search',
    'route': 'Route',
    'quiz': 'HelpCircle',
    'logout': 'LogOut',
    'lock': 'Lock',
    'error': 'AlertCircle',
    'chevron_right': 'ChevronRight',
    'check_circle': 'CheckCircle2',
    'arrow_forward': 'ArrowRight',
    'arrow_back': 'ArrowLeft',
    'warning': 'AlertTriangle',
    'verified_user': 'ShieldCheck',
    'tune': 'Sliders',
    'play_arrow': 'Play',
    'notifications': 'Bell',
    'monitoring': 'Activity',
    'menu_book': 'BookOpen',
    'login': 'LogIn',
    'hub': 'Share2',
    'grid_view': 'Grid',
    'forum': 'MessageSquare',
    'exercise': 'Dumbbell',
    'close': 'X',
    'assessment': 'FileText',
    'topic': 'Hash',
    'timer': 'Timer',
    'timeline': 'GitCommit',
    'thumb_up': 'ThumbsUp',
    'terminal': 'Terminal',
    'support_agent': 'Headset',
    'share': 'Share',
    'sentiment_dissatisfied': 'Frown',
    'send': 'Send',
    'schema': 'Database',
    'replay': 'RotateCcw',
    'print': 'Printer',
    'pie_chart': 'PieChart',
    'person_search': 'UserSearch',
    'person_off': 'UserMinus',
    'open_in_new': 'ExternalLink',
    'neurology': 'Brain',
    'mic': 'Mic',
    'menu': 'Menu',
    'mail': 'Mail',
    'lock_reset': 'KeyRound',
    'local_fire_department': 'Flame',
    'list_alt': 'List',
    'lightbulb': 'Lightbulb',
    'key': 'Key',
    'inventory_2': 'Archive',
    'insights': 'LineChart',
    'info': 'Info',
    'how_to_reg': 'UserCheck',
    'home': 'Home',
    'group': 'Users',
    'folder_managed': 'FolderCog',
    'flag': 'Flag',
    'filter_alt': 'Filter',
    'error_outline': 'AlertCircle',
    'donut_large': 'PieChart',
    'do_not_disturb_off': 'Ban',
    'check': 'Check',
    'chat_bubble': 'MessageCircle',
    'bookmark': 'Bookmark',
    'block': 'Ban',
    'badge': 'Badge',
    'auto_stories': 'BookOpen',
    'attach_file': 'Paperclip',
    'assignment': 'ClipboardList',
    'arrow_upward': 'ArrowUp',
    'analytics': 'BarChart2',
    'admin_panel_settings': 'ShieldAlert',
    'account_circle': 'UserCircle',
    'bolt': 'Zap',
    'article': 'FileText',
    'code': 'Code',
    'history': 'History',
    'settings': 'Settings',
    'visibility': 'Eye',
    'visibility_off': 'EyeOff',
    'favorite': 'Heart',
    'favorite_border': 'Heart',
    'star': 'Star',
    'star_border': 'Star',
    'star_half': 'StarHalf',
    'more_vert': 'MoreVertical',
    'more_horiz': 'MoreHorizontal',
    'design_services': 'PencilRuler',
    'dashboard_customize': 'LayoutGrid',
    'data_object': 'Braces',
};

export default function Icon({ name, className = "", style = {} }) {
    if (!name) return null;
    
    // Strip material-symbols-outlined from className to avoid inherited unwanted font styles
    const finalClassName = className.replace(/material-symbols-outlined/g, '').trim();

    // Convert material name to Lucide component name
    const lucideName = materialToLucide[name] || 'HelpCircle';
    const LucideComponent = LucideIcons[lucideName];

    if (!LucideComponent) return null;

    // Use size="1em" to inherit font-size from parent or tailwind text-xx classes
    // This perfectly mimics how an icon font behaves in a span
    return <LucideComponent size="1em" className={finalClassName} style={style} />;
}
