name: judge0-v1130

x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  server:
    image: ${JUDGE0_IMAGE:-mrkushalsm/judge0:cgv2}
    volumes:
      - ../../.run/prod/judge0.conf:/judge0.conf:ro
    ports:
      - "127.0.0.1:2358:2358"
    privileged: true
    cgroup: host
    restart: always
    <<: *default-logging

  workers:
    image: ${JUDGE0_IMAGE:-mrkushalsm/judge0:cgv2}
    command: ["./scripts/workers"]
    volumes:
      - ../../.run/prod/judge0.conf:/judge0.conf:ro
    privileged: true
    cgroup: host
    restart: always
    <<: *default-logging

  db:
    image: postgres:13.0
    env_file: ../../.run/prod/judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always
    <<: *default-logging

  redis:
    image: redis:6.0
    command:
      - bash
      - -c
      - docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"
    env_file: ../../.run/prod/judge0.conf
    volumes:
      - redis-data:/data
    restart: always
    <<: *default-logging

volumes:
  postgres-data:
  redis-data:
